name: GitHub-Profile-Summary-Cards

on:
  schedule: # 每天零点自动更新
    - cron: "0 0 * * *"
  workflow_dispatch: # 允许你手动点击按钮立即更新

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          THEME: github_dark
          UTC_OFFSET: 8
